// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6I8lgA1sNYE3uiCSMKRLXTyAus8xbf0',
    appId: '1:480489289206:web:854f8d775634a1ca5e03d7',
    messagingSenderId: '480489289206',
    projectId: 'the-butters-mobile-app',
    authDomain: 'the-butters-mobile-app.firebaseapp.com',
    storageBucket: 'the-butters-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilw45xDE__LLHBaWBJqHHCjK5B3k8Ffw',
    appId: '1:480489289206:android:bee5630abbb5a3715e03d7',
    messagingSenderId: '480489289206',
    projectId: 'the-butters-mobile-app',
    storageBucket: 'the-butters-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJUIZLQQBinLnf7O8VHLObt7WOFriL4c',
    appId: '1:480489289206:ios:eb3b30bfdf5b48755e03d7',
    messagingSenderId: '480489289206',
    projectId: 'the-butters-mobile-app',
    storageBucket: 'the-butters-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.thebuttersCardapioMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJUIZLQQBinLnf7O8VHLObt7WOFriL4c',
    appId: '1:480489289206:ios:eb3b30bfdf5b48755e03d7',
    messagingSenderId: '480489289206',
    projectId: 'the-butters-mobile-app',
    storageBucket: 'the-butters-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.thebuttersCardapioMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6I8lgA1sNYE3uiCSMKRLXTyAus8xbf0',
    appId: '1:480489289206:web:762ea80c92ceabb25e03d7',
    messagingSenderId: '480489289206',
    projectId: 'the-butters-mobile-app',
    authDomain: 'the-butters-mobile-app.firebaseapp.com',
    storageBucket: 'the-butters-mobile-app.firebasestorage.app',
  );
}
